from __future__ import annotations

import hashlib
import json
import mimetypes
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd
from fastapi import APIRouter

from app.sidecar.schemas import (
    CodeConsoleContextRequest,
    CodeConsoleContextResponse,
    CodeConsoleRunRequest,
    CodeConsoleRunResponse,
)
from app.sidecar.server_utils import http_bad_request, normalize_path
from src.code_console_service import build_code_console_context, run_code_console_script
from src.rendering.data_containers import table_container_from_frame


def _sha256_path(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest() if path.exists() else ""


def _artifact_kind(path: Path) -> str:
    suffix = path.suffix.lower()
    if suffix in {".pdf", ".png", ".jpg", ".jpeg", ".tif", ".tiff"}:
        return "figure"
    if suffix in {".csv", ".json"}:
        return "table"
    return "artifact"


def _artifact_payload(
    *,
    artifact_id: str,
    source_graph_node_id: str,
    kind: str,
    label: str,
    path: Path,
    data_container_id: str | None = None,
) -> dict[str, object]:
    mime_type, _ = mimetypes.guess_type(path.name)
    return {
        "artifact_id": artifact_id,
        "source_module": "code_console",
        "source_graph_node_id": source_graph_node_id,
        "kind": kind,
        "label": label,
        "mime_type": mime_type or ("text/plain" if kind == "log" else "application/octet-stream"),
        "sha256": _sha256_path(path),
        "embedded_path": f"artifacts/code_console/latest_run/{path.name}",
        "manifest_id": artifact_id,
        "created_at": datetime.now(UTC).isoformat(),
        "status": "enabled" if path.exists() else "missing",
        "help": "Code Console generated artifact managed through the project bundle manifest.",
        "data_container_id": data_container_id,
    }


def _notebook_outputs_containers_artifacts(
    result,
) -> tuple[list[dict[str, object]], list[dict[str, object]], list[dict[str, object]]]:
    outputs: list[dict[str, object]] = []
    containers: list[dict[str, object]] = []
    artifacts: list[dict[str, object]] = []
    for index, item in enumerate(result.generated_files, start=1):
        output_id = f"notebook-output:{index}"
        path = Path(item.path)
        suffix = path.suffix.lower()
        source_graph_node_id = f"code_console:notebook_output:{index}"
        artifact_id = f"artifact:code_console:{result.run_dir.name}:{index}"
        if suffix in {".pdf", ".png", ".jpg", ".jpeg", ".tif", ".tiff"}:
            outputs.append(
                {
                    "id": output_id,
                    "kind": "figure",
                    "label": item.name,
                    "status": "enabled",
                    "source_run_id": str(result.run_dir.name),
                    "artifact_paths": [str(path)],
                    "container_ids": [],
                    "help": "Code Console generated figure output.",
                }
            )
            artifacts.append(
                _artifact_payload(
                    artifact_id=artifact_id,
                    source_graph_node_id=source_graph_node_id,
                    kind="figure",
                    label=item.name,
                    path=path,
                )
            )
            continue
        frame: pd.DataFrame | None = None
        if suffix == ".csv":
            frame = pd.read_csv(path)
        elif suffix == ".json":
            payload = json.loads(path.read_text(encoding="utf-8"))
            records = payload.get("records") if isinstance(payload, dict) else payload
            if isinstance(records, list):
                frame = pd.DataFrame(records)
        if frame is None:
            outputs.append(
                {
                    "id": output_id,
                    "kind": _artifact_kind(path),
                    "label": item.name,
                    "status": "enabled",
                    "source_run_id": str(result.run_dir.name),
                    "artifact_paths": [str(path)],
                    "container_ids": [],
                    "help": "Code Console generated artifact output.",
                }
            )
            artifacts.append(
                _artifact_payload(
                    artifact_id=artifact_id,
                    source_graph_node_id=source_graph_node_id,
                    kind=_artifact_kind(path),
                    label=item.name,
                    path=path,
                )
            )
            continue
        container_id = f"notebook-output-container:{index}"
        containers.append(
            table_container_from_frame(
                frame,
                input_path=path,
                container_id=container_id,
                label=item.name,
                status="enabled",
                kind="notebook_output",
                help_text="Readonly table generated by Code Console.",
            )
        )
        outputs.append(
            {
                "id": output_id,
                "kind": "table",
                "label": item.name,
                "status": "enabled",
                "source_run_id": str(result.run_dir.name),
                "artifact_paths": [str(path)],
                "container_ids": [container_id],
                "help": "Code Console generated table output.",
            }
        )
        artifacts.append(
            _artifact_payload(
                artifact_id=artifact_id,
                source_graph_node_id=source_graph_node_id,
                kind="table",
                label=item.name,
                path=path,
                data_container_id=container_id,
            )
        )
    if result.stdout:
        stdout_path = Path(result.stdout_path)
        artifacts.append(
            _artifact_payload(
                artifact_id=f"artifact:code_console:{result.run_dir.name}:stdout",
                source_graph_node_id="code_console:latest_run:stdout",
                kind="log",
                label="stdout.log",
                path=stdout_path,
            )
        )
        outputs.append(
            {
                "id": "notebook-output:stdout",
                "kind": "log",
                "label": "stdout.log",
                "status": "enabled",
                "source_run_id": str(result.run_dir.name),
                "artifact_paths": [str(stdout_path)],
                "container_ids": [],
                "help": "Code Console stdout log artifact.",
            }
        )
    if result.stderr:
        stderr_path = Path(result.stderr_path)
        artifacts.append(
            _artifact_payload(
                artifact_id=f"artifact:code_console:{result.run_dir.name}:stderr",
                source_graph_node_id="code_console:latest_run:stderr",
                kind="log",
                label="stderr.log",
                path=stderr_path,
            )
        )
        outputs.append(
            {
                "id": "notebook-output:stderr",
                "kind": "log",
                "label": "stderr.log",
                "status": "enabled",
                "source_run_id": str(result.run_dir.name),
                "artifact_paths": [str(stderr_path)],
                "container_ids": [],
                "help": "Code Console stderr log artifact.",
            }
        )
    return outputs, containers, artifacts


def create_code_console_router() -> APIRouter:
    router = APIRouter()

    @router.post("/code-console/context", response_model=CodeConsoleContextResponse)
    def code_console_context(request: CodeConsoleContextRequest) -> CodeConsoleContextResponse:
        try:
            input_path = normalize_path(request.input_path)
            context = build_code_console_context(
                input_path=input_path,
                sheet=request.sheet,
                template=request.template,
                size=request.options.size,
                style_preset=request.options.style_preset,
                palette_preset=request.options.palette_preset,
                visual_theme_id=request.options.visual_theme_id,
                source_kind=request.source_kind,
                source_label=request.source_label,
            )
            return CodeConsoleContextResponse.model_validate(
                {
                    "context_id": context.context_id,
                    "input_path": str(context.input_path),
                    "sheet": context.sheet,
                    "sheet_names": list(context.sheet_names),
                    "inspection": context.inspection,
                    "dataset": context.dataset,
                    "template": context.template,
                    "options": {
                        "size": context.options["size"],
                        "style_preset": context.options["style_preset"],
                        "palette_preset": context.options["palette_preset"],
                        "visual_theme_id": context.options["visual_theme_id"],
                    },
                    "prompt_text": context.prompt_text,
                    "starter_code": context.starter_code,
                    "source_kind": context.source_kind,
                    "source_label": context.source_label,
                }
            )
        except Exception as exc:
            raise http_bad_request("code-console-context", exc) from exc

    @router.post("/code-console/run", response_model=CodeConsoleRunResponse)
    def code_console_run(request: CodeConsoleRunRequest) -> CodeConsoleRunResponse:
        try:
            request_context = request.context
            input_path = normalize_path(request_context.input_path) if request_context else None
            result = run_code_console_script(
                context_id=request.context_id,
                input_path=input_path,
                sheet=request_context.sheet if request_context else None,
                template=request_context.template if request_context else None,
                size=request_context.options.size if request_context else None,
                style_preset=request_context.options.style_preset if request_context else None,
                palette_preset=request_context.options.palette_preset if request_context else None,
                visual_theme_id=request_context.options.visual_theme_id if request_context else None,
                code=request.code,
                timeout_seconds=request.timeout_seconds,
                source_kind=request_context.source_kind if request_context else None,
                source_label=request_context.source_label if request_context else None,
            )
            notebook_outputs, data_containers, notebook_artifacts = _notebook_outputs_containers_artifacts(result)
            return CodeConsoleRunResponse.model_validate(
                {
                    "status": result.status,
                    "exit_code": result.exit_code,
                    "duration_seconds": result.duration_seconds,
                    "stdout": result.stdout,
                    "stderr": result.stderr,
                    "run_dir": str(result.run_dir),
                    "output_dir": str(result.output_dir),
                    "script_path": str(result.script_path),
                    "prompt_path": str(result.prompt_path),
                    "context_path": str(result.context_path),
                    "stdout_path": str(result.stdout_path),
                    "stderr_path": str(result.stderr_path),
                    "generated_files": [
                        {
                            "path": str(item.path),
                            "name": item.name,
                            "file_type": item.file_type,
                            "size_bytes": item.size_bytes,
                        }
                        for item in result.generated_files
                    ],
                    "notebook_outputs": notebook_outputs,
                    "notebook_artifacts": notebook_artifacts,
                    "data_containers": data_containers,
                }
            )
        except Exception as exc:
            raise http_bad_request("code-console-run", exc) from exc

    return router


__all__ = ["create_code_console_router"]
