from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
from fastapi import APIRouter

from app.sidecar.schemas import (
    CodeConsoleContextRequest,
    CodeConsoleContextResponse,
    CodeConsoleRunRequest,
    CodeConsoleRunResponse,
)
from app.sidecar.server_utils import http_bad_request, normalize_path
from src.code_console_service import build_code_console_context, run_code_console_script
from src.rendering.data_containers import table_container_from_frame


def _notebook_outputs_and_containers(result) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    outputs: list[dict[str, object]] = []
    containers: list[dict[str, object]] = []
    for index, item in enumerate(result.generated_files, start=1):
        output_id = f"notebook-output:{index}"
        path = Path(item.path)
        suffix = path.suffix.lower()
        if suffix in {".pdf", ".png", ".jpg", ".jpeg", ".tif", ".tiff"}:
            outputs.append(
                {
                    "id": output_id,
                    "kind": "figure",
                    "label": item.name,
                    "status": "experimental",
                    "source_run_id": str(result.run_dir.name),
                    "artifact_paths": [str(path)],
                    "container_ids": [],
                    "help": "Code Console generated figure output.",
                }
            )
            continue
        frame: pd.DataFrame | None = None
        if suffix == ".csv":
            frame = pd.read_csv(path)
        elif suffix == ".json":
            payload = json.loads(path.read_text(encoding="utf-8"))
            records = payload.get("records") if isinstance(payload, dict) else payload
            if isinstance(records, list):
                frame = pd.DataFrame(records)
        if frame is None:
            outputs.append(
                {
                    "id": output_id,
                    "kind": "artifact",
                    "label": item.name,
                    "status": "experimental",
                    "source_run_id": str(result.run_dir.name),
                    "artifact_paths": [str(path)],
                    "container_ids": [],
                    "help": "Code Console generated artifact output.",
                }
            )
            continue
        container_id = f"notebook-output-container:{index}"
        containers.append(
            table_container_from_frame(
                frame,
                input_path=path,
                container_id=container_id,
                label=item.name,
                status="experimental",
                kind="notebook_output",
                help_text="Readonly table generated by Code Console.",
            )
        )
        outputs.append(
            {
                "id": output_id,
                "kind": "table",
                "label": item.name,
                "status": "experimental",
                "source_run_id": str(result.run_dir.name),
                "artifact_paths": [str(path)],
                "container_ids": [container_id],
                "help": "Code Console generated table output.",
            }
        )
    return outputs, containers


def create_code_console_router() -> APIRouter:
    router = APIRouter()

    @router.post("/code-console/context", response_model=CodeConsoleContextResponse)
    def code_console_context(request: CodeConsoleContextRequest) -> CodeConsoleContextResponse:
        try:
            input_path = normalize_path(request.input_path)
            context = build_code_console_context(
                input_path=input_path,
                sheet=request.sheet,
                template=request.template,
                size=request.options.size,
                style_preset=request.options.style_preset,
                palette_preset=request.options.palette_preset,
                visual_theme_id=request.options.visual_theme_id,
                source_kind=request.source_kind,
                source_label=request.source_label,
            )
            return CodeConsoleContextResponse.model_validate(
                {
                    "context_id": context.context_id,
                    "input_path": str(context.input_path),
                    "sheet": context.sheet,
                    "sheet_names": list(context.sheet_names),
                    "inspection": context.inspection,
                    "dataset": context.dataset,
                    "template": context.template,
                    "options": {
                        "size": context.options["size"],
                        "style_preset": context.options["style_preset"],
                        "palette_preset": context.options["palette_preset"],
                        "visual_theme_id": context.options["visual_theme_id"],
                    },
                    "prompt_text": context.prompt_text,
                    "starter_code": context.starter_code,
                    "source_kind": context.source_kind,
                    "source_label": context.source_label,
                }
            )
        except Exception as exc:
            raise http_bad_request("code-console-context", exc) from exc

    @router.post("/code-console/run", response_model=CodeConsoleRunResponse)
    def code_console_run(request: CodeConsoleRunRequest) -> CodeConsoleRunResponse:
        try:
            request_context = request.context
            input_path = normalize_path(request_context.input_path) if request_context else None
            result = run_code_console_script(
                context_id=request.context_id,
                input_path=input_path,
                sheet=request_context.sheet if request_context else None,
                template=request_context.template if request_context else None,
                size=request_context.options.size if request_context else None,
                style_preset=request_context.options.style_preset if request_context else None,
                palette_preset=request_context.options.palette_preset if request_context else None,
                visual_theme_id=request_context.options.visual_theme_id if request_context else None,
                code=request.code,
                timeout_seconds=request.timeout_seconds,
                source_kind=request_context.source_kind if request_context else None,
                source_label=request_context.source_label if request_context else None,
            )
            notebook_outputs, data_containers = _notebook_outputs_and_containers(result)
            return CodeConsoleRunResponse.model_validate(
                {
                    "status": result.status,
                    "exit_code": result.exit_code,
                    "duration_seconds": result.duration_seconds,
                    "stdout": result.stdout,
                    "stderr": result.stderr,
                    "run_dir": str(result.run_dir),
                    "output_dir": str(result.output_dir),
                    "script_path": str(result.script_path),
                    "prompt_path": str(result.prompt_path),
                    "context_path": str(result.context_path),
                    "stdout_path": str(result.stdout_path),
                    "stderr_path": str(result.stderr_path),
                    "generated_files": [
                        {
                            "path": str(item.path),
                            "name": item.name,
                            "file_type": item.file_type,
                            "size_bytes": item.size_bytes,
                        }
                        for item in result.generated_files
                    ],
                    "notebook_outputs": notebook_outputs,
                    "data_containers": data_containers,
                }
            )
        except Exception as exc:
            raise http_bad_request("code-console-run", exc) from exc

    return router


__all__ = ["create_code_console_router"]
