"""Sidecar schema facade."""

# ruff: noqa: F401, I001

from __future__ import annotations

from app.sidecar.schemas_common import (
    HealthResponse,
    PathResponse,
    PreviewItemResponse,
    QAReportResponse,
    QAIssueResponse,
    StrictModel,
    SubmissionCheckResponse,
    SubmissionReportResponse,
    serialize_dataclass,
)
from app.sidecar.schemas_composer import (
    ComposerImportRequest,
    ComposerPreviewResponse,
    ComposerProjectResponse,
    ComposerRequest,
    PanelThumbnailResponse,
    ThumbnailRequest,
    composer_project_from_request,
)
from app.sidecar.schemas_render import (
    ExportRenderRequest,
    ExportRenderResponse,
    FileRequest,
    InputInspectionResponse,
    InspectFileResponse,
    PlotCandidateRolesResponse,
    PlotColumnProfileResponse,
    PlotDatasetPreviewResponse,
    PreflightRenderResponse,
    PreflightResultResponse,
    RecommendationResponse,
    RenderOptionsPayload,
    RenderPreviewResponse,
    RenderRequest,
    TemplateRecommendationResponse,
    rendered_plots_to_preview_payload,
)
from app.sidecar.schemas_tensile import (
    TensileComparisonExportRequest,
    TensileComparisonExportResponse,
    TensileMetricSummaryResponse,
    TensileReplicateRequest,
    TensileReplicateResponseModel,
    TensileWorkbookRequest,
    TensileWorkbookSummaryResponse,
)

__all__ = [
    "ComposerImportRequest",
    "ComposerPreviewResponse",
    "ComposerProjectResponse",
    "ComposerRequest",
    "ExportRenderRequest",
    "ExportRenderResponse",
    "FileRequest",
    "HealthResponse",
    "InspectFileResponse",
    "InputInspectionResponse",
    "PathResponse",
    "PanelThumbnailResponse",
    "PlotCandidateRolesResponse",
    "PlotColumnProfileResponse",
    "PlotDatasetPreviewResponse",
    "PreflightRenderResponse",
    "PreflightResultResponse",
    "PreviewItemResponse",
    "QAReportResponse",
    "QAIssueResponse",
    "RecommendationResponse",
    "RenderOptionsPayload",
    "RenderPreviewResponse",
    "RenderRequest",
    "StrictModel",
    "SubmissionCheckResponse",
    "SubmissionReportResponse",
    "TensileComparisonExportRequest",
    "TensileComparisonExportResponse",
    "TensileMetricSummaryResponse",
    "TensileReplicateRequest",
    "TensileReplicateResponseModel",
    "TensileWorkbookRequest",
    "TensileWorkbookSummaryResponse",
    "TemplateRecommendationResponse",
    "composer_project_from_request",
    "rendered_plots_to_preview_payload",
    "serialize_dataclass",
    "ThumbnailRequest",
]
