from __future__ import annotations

# ruff: noqa: E501
from typing import Any


def _capability(
    *,
    id: str,
    label: str,
    status: str,
    owner: str,
    surface: str,
    help: str,
    introduced_in: str = "runtime_landing",
    typed_payload_schema: dict[str, Any] | None = None,
    test_requirements: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "id": id,
        "label": label,
        "status": status,
        "owner": owner,
        "surface": surface,
        "typed_payload_schema": typed_payload_schema or {"type": "object"},
        "help": help,
        "introduced_in": introduced_in,
        "test_requirements": test_requirements or ["schema_decode", "metadata_presence"],
    }


def capability_catalog_payload() -> list[dict[str, Any]]:
    no_payload_schema = {"type": "object", "additionalProperties": False}
    return [
        {
            "id": "data_containers",
            "label": "Data Containers",
            "description": "Typed table, matrix, transformed view, statistics, fit result, and notebook containers.",
            "capabilities": [
                _capability(
                    id="data.table",
                    label="Table",
                    status="enabled",
                    owner="sidecar",
                    surface="plot,data_studio,code_console",
                    help="Readonly table containers are generated by source, import, analysis, and notebook routes.",
                ),
                _capability(
                    id="data.matrix",
                    label="Matrix",
                    status="enabled",
                    owner="sidecar",
                    surface="plot,data_studio",
                    help="Matrix containers are generated for XYZ scalar fields and explicit binary/raw previews with contour-ready dimensions and coordinate vectors.",
                ),
                _capability(
                    id="data.transformed_view",
                    label="Transformed View",
                    status="enabled",
                    owner="sidecar",
                    surface="plot,data_studio",
                    help="Typed transforms and analysis operations produce readonly transformed-view containers.",
                ),
                _capability(
                    id="data.statistics_summary",
                    label="Statistics Summary",
                    status="enabled",
                    owner="sidecar",
                    surface="plot,data_studio",
                    help="Sidecar-generated statistics summaries are available as container payloads.",
                ),
                _capability(
                    id="data.fit_result",
                    label="Fit Result",
                    status="enabled",
                    owner="sidecar",
                    surface="plot,data_studio",
                    help="Fit results are exposed through the shared analysis result envelope.",
                ),
                _capability(
                    id="data.notebook_output",
                    label="Notebook Output",
                    status="enabled",
                    owner="sidecar",
                    surface="code_console",
                    help="Code Console generated figures and tables are exposed as notebook output containers.",
                ),
                _capability(
                    id="data.column_model",
                    label="Column Model",
                    status="enabled",
                    owner="sidecar",
                    surface="plot,data_studio,analysis,code_console",
                    help="Data containers expose column ids, modes, role hints, units, readonly state, lineage, missing policy, and lifecycle events.",
                ),
            ],
        },
        {
            "id": "command_engine",
            "label": "Command Engine",
            "description": "Cross-module typed commands for graph revisions and native undo replay.",
            "capabilities": [
                _capability(id="command.cross_module_normalize", label="Cross-Module Normalize", status="enabled", owner="sidecar", surface="all", help="POST /command/normalize validates add/edit/delete/reorder/rename/visibility/lock/copy-settings and module handoff commands."),
                _capability(id="command.apply_preview", label="Apply Preview", status="enabled", owner="sidecar", surface="all", help="POST /command/apply-preview emits graph patch metadata and render invalidation without saving project files."),
                _capability(id="command.compound", label="Compound Commands", status="enabled", owner="sidecar", surface="all", help="Compound command ids are accepted for import/bind/template and multi-object edits."),
            ],
        },
        {
            "id": "plot_objects",
            "label": "Plot Objects",
            "description": "Graph-addressable plot scene objects and render payload features.",
            "capabilities": [
                _capability(id="plot.series", label="Series", status="enabled", owner="shared", surface="plot", help="Series are graph-addressable plot objects."),
                _capability(id="plot.axis", label="Axis", status="enabled", owner="shared", surface="plot", help="Axes are graph-addressable plot objects."),
                _capability(id="plot.legend", label="Legend", status="enabled", owner="shared", surface="plot", help="Legend state is represented by typed payloads."),
                _capability(id="plot.guide.line", label="Reference Guide", status="enabled", owner="shared", surface="plot", help="Reference guide lines and bands are persisted in render_options.reference_guides."),
                _capability(id="plot.guide", label="Guide Object", status="enabled", owner="shared", surface="plot", help="Guide objects are graph-addressable wrappers for guide payloads."),
                _capability(id="plot.annotation.text", label="Text Annotation", status="enabled", owner="shared", surface="plot", help="Text annotations are persisted in render_options.text_annotations."),
                _capability(id="plot.annotation.shape", label="Shape Annotation", status="enabled", owner="shared", surface="plot", help="Shape annotations are persisted in render_options.shape_annotations."),
                _capability(id="plot.layer.function", label="Function Layer", status="enabled", owner="sidecar", surface="plot", help="Function layers use backend expression parsing through analytical_layers."),
                _capability(id="plot.axis.extra", label="Extra Axis", status="enabled", owner="shared", surface="plot", help="Extra axes are persisted through extra_x_axis and extra_y_axis payloads."),
                _capability(id="plot.axis.break", label="Broken Axis", status="enabled", owner="sidecar", surface="plot", help="Broken axis intervals are persisted through x_axis_breaks and y_axis_breaks."),
                _capability(id="plot.fit_overlay", label="Fit Overlay", status="enabled", owner="sidecar", surface="plot,data_studio", help="Fit overlays are graph-addressable objects backed by fit analysis results."),
                _capability(id="plot.page", label="Plot Page", status="enabled", owner="shared", surface="plot,composer", help="Plot page objects provide stable graph identity."),
                _capability(id="plot.plot_area", label="Plot Area", status="enabled", owner="shared", surface="plot", help="Plot area objects provide stable graph identity for scene-local layout and selection."),
            ],
        },
        {
            "id": "analysis_operations",
            "label": "Analysis Operations",
            "description": "Sidecar-owned numerical operations with a common result envelope.",
            "capabilities": [
                _capability(id="analysis.fit", label="Fit", status="enabled", owner="sidecar", surface="plot,data_studio", help="Current fit models are available through POST /fit-analysis."),
                _capability(id="analysis.smoothing", label="Smoothing", status="enabled", owner="sidecar", surface="plot,data_studio", help="Rolling mean, rolling median, and Savitzky-Golay smoothing are available through POST /analysis-operation."),
                _capability(id="analysis.interpolation", label="Interpolation", status="enabled", owner="sidecar", surface="plot,data_studio", help="Linear and cubic interpolation are available through POST /analysis-operation."),
                _capability(id="analysis.differentiation", label="Differentiation", status="enabled", owner="sidecar", surface="plot,data_studio", help="Gradient-based differentiation is available through POST /analysis-operation."),
                _capability(id="analysis.integration", label="Integration", status="enabled", owner="sidecar", surface="plot,data_studio", help="Trapezoid cumulative and total integration are available through POST /analysis-operation."),
                _capability(id="analysis.fft", label="FFT", status="enabled", owner="sidecar", surface="plot,data_studio", help="FFT magnitude analysis is available through POST /analysis-operation."),
                _capability(id="analysis.fourier_filter", label="Fourier Filter", status="enabled", owner="sidecar", surface="plot,data_studio", help="Frequency-domain low/high-pass filtering is available through POST /analysis-operation."),
                _capability(id="analysis.correlation", label="Correlation", status="enabled", owner="sidecar", surface="plot,data_studio", help="Correlation is available through POST /analysis-operation."),
                _capability(id="analysis.convolution", label="Convolution", status="enabled", owner="sidecar", surface="plot,data_studio", help="Convolution is available through POST /analysis-operation."),
                _capability(id="analysis.baseline", label="Baseline Correction", status="enabled", owner="sidecar", surface="plot,data_studio", help="Polynomial baseline correction is available through POST /analysis-operation."),
                _capability(id="analysis.peak_detection", label="Peak Detection", status="enabled", owner="sidecar", surface="plot,data_studio", help="Peak detection is available through POST /analysis-operation."),
                _capability(id="analysis.kde", label="KDE", status="enabled", owner="sidecar", surface="plot,data_studio", help="Gaussian KDE is available through POST /analysis-operation."),
                _capability(id="analysis.statistical_tests", label="Statistical Tests", status="enabled", owner="sidecar", surface="plot,data_studio", help="T-test, Mann-Whitney, and Shapiro diagnostics are available through POST /analysis-operation."),
                _capability(id="analysis.distribution_fitting", label="Distribution Fitting", status="enabled", owner="sidecar", surface="plot,data_studio", help="Normal, lognormal, and exponential distribution fits are available through POST /analysis-operation."),
                _capability(id="analysis.peak_fitting", label="Peak Fitting", status="enabled", owner="sidecar", surface="plot,data_studio", help="Single Gaussian peak fitting is available through POST /analysis-operation."),
                _capability(id="analysis.growth_models", label="Growth Models", status="enabled", owner="sidecar", surface="plot,data_studio", help="Exponential and logistic growth fits are available through POST /analysis-operation."),
            ],
        },
        {
            "id": "import_filters",
            "label": "Import Filters",
            "description": "Source preview and import filters with typed options and diagnostics.",
            "capabilities": [
                _capability(id="import.csv", label="CSV/TSV/TXT", status="enabled", owner="sidecar", surface="plot,data_studio", help="Delimited text import is available through inspect, source preview, and import preview routes."),
                _capability(id="import.excel", label="Excel", status="enabled", owner="sidecar", surface="plot,data_studio", help="Workbook import is available through source preview and import preview routes."),
                _capability(id="import.json", label="JSON", status="enabled", owner="sidecar", surface="plot,data_studio", help="JSON records/table preview is available through POST /import-preview."),
                _capability(id="import.sql", label="SQL", status="disabled", owner="sidecar", surface="data_studio", help="SQL import is disabled until safe connection, credential, and preview-only policies are implemented."),
                _capability(id="import.hdf5", label="HDF5", status="disabled", owner="sidecar", surface="plot,data_studio", help="HDF5 import is disabled because the h5py runtime dependency is not installed."),
                _capability(id="import.netcdf", label="NetCDF", status="disabled", owner="sidecar", surface="plot,data_studio", help="NetCDF import is disabled because the netCDF4 runtime dependency is not installed."),
                _capability(id="import.fits", label="FITS", status="disabled", owner="sidecar", surface="plot,data_studio", help="FITS import is disabled because the astropy runtime dependency is not installed."),
                _capability(id="import.ods", label="ODS", status="disabled", owner="sidecar", surface="plot,data_studio", help="ODS import is disabled because the odf runtime dependency is not installed."),
                _capability(id="import.readstat", label="SAS/Stata/SPSS", status="disabled", owner="sidecar", surface="data_studio", help="ReadStat-backed import is disabled because pyreadstat is not installed."),
                _capability(id="import.binary_raw", label="Binary/Raw", status="enabled", owner="sidecar", surface="plot,data_studio", help="Binary/raw preview is available with explicit dtype and shape options."),
                _capability(id="import.origin_scidavis_eval", label="Origin/SciDAVis Evaluation", status="disabled", owner="sidecar", surface="project", help="Origin/SciDAVis-style project import is an evaluation backlog item, not runtime support."),
                _capability(id="import.image_digitizer", label="Image Digitizer", status="disabled", owner="sidecar", surface="plot", help="Image digitizer support is disabled until a dedicated workflow and validation fixtures exist."),
            ],
        },
        {
            "id": "export_targets",
            "label": "Export Targets",
            "description": "Figure, data, project, comparison, and artifact export targets.",
            "capabilities": [
                _capability(id="export.figure.pdf", label="Figure PDF", status="enabled", owner="sidecar", surface="plot,composer,code_console", help="PDF figure export is the authoritative vector output path."),
                _capability(id="export.figure.tiff", label="Figure TIFF", status="enabled", owner="sidecar", surface="plot,composer,code_console", help="TIFF figure export is the authoritative raster publication output path."),
                _capability(id="export.data_workbook", label="Data Workbook", status="enabled", owner="sidecar", surface="plot,data_studio", help="Container-backed workbook export has manifest-aware runtime helpers."),
                _capability(id="export.project_bundle", label="Project Bundle", status="enabled", owner="sidecar", surface="all", help=".sciplot project bundles are the self-contained app-level project format."),
                _capability(id="export.comparison_bundle", label="Comparison Bundle", status="enabled", owner="sidecar", surface="data_studio", help="Data Studio comparison export emits workbooks, figures, and filtered standard outputs."),
                _capability(id="export.artifact_manifest", label="Artifact Manifest", status="enabled", owner="sidecar", surface="all", help="Manifest-driven artifact sets are available as sidecar helpers."),
                _capability(id="export.code_console_figure_set", label="Code Console Figure Set", status="enabled", owner="sidecar", surface="code_console", help="Code Console generated figure sets are available through latest-run artifact manifests."),
            ],
        },
        {
            "id": "project_bundle_features",
            "label": "Project Bundle Features",
            "description": "Project save/open features exposed for compatibility and migration handling.",
            "capabilities": [
                _capability(id="project_bundle.document_graph", label="Document Graph", status="enabled", owner="sidecar", surface="all", help="Project bundles include an internal document_graph for durable object identity."),
                _capability(id="project_bundle.embedded_sources", label="Embedded Sources", status="enabled", owner="sidecar", surface="all", help="Project restore uses embedded bundle sources instead of original absolute paths."),
            ],
        },
        {
            "id": "native_preview_features",
            "label": "Native Preview Features",
            "description": "Contract-gated macOS native preview and interaction capabilities.",
            "capabilities": [
                _capability(id="native_preview.preview_scene", label="Preview Scene", status="enabled", owner="sidecar", surface="plot", help="POST /preview-scene returns a contract-gated scene payload for Swift Canvas realtime preview."),
                _capability(id="native_preview.curve_hit_testing", label="Curve Hit Testing", status="enabled", owner="shared", surface="plot", help="Curve hit testing uses backend interaction metadata when available."),
                _capability(id="native_preview.unavailable_fallback", label="Backend Fallback", status="enabled", owner="shared", surface="plot", typed_payload_schema=no_payload_schema, help="Unsupported native preview cases fall back to backend bitmap/PDF preview."),
            ],
        },
        {
            "id": "live_sources",
            "label": "Live Sources",
            "description": "LabPlot-inspired realtime data source capabilities with SciPlot-safe v1 scope.",
            "capabilities": [
                _capability(id="live.file_tail", label="File Tail", status="enabled", owner="sidecar", surface="plot,data_studio", help="File-tail live source payloads are supported for append/replace preview workflows."),
                _capability(id="live.folder_watch", label="Folder Watch", status="enabled", owner="sidecar", surface="data_studio", help="Folder-watch live source payloads are available for controlled periodic refresh."),
                _capability(id="live.periodic_csv", label="Periodic CSV Refresh", status="enabled", owner="sidecar", surface="plot,data_studio", help="Periodic CSV refresh is represented as a live source payload and graph data revision."),
                _capability(id="live.mqtt", label="MQTT", status="disabled", owner="sidecar", surface="data_studio", help="MQTT is disabled until connection policy, credentials, fixtures, and UI controls are implemented."),
                _capability(id="live.serial", label="Serial Port", status="disabled", owner="sidecar", surface="data_studio", help="Serial port live data is disabled until sandbox, permissions, and fixtures are implemented."),
                _capability(id="live.socket", label="Socket", status="disabled", owner="sidecar", surface="data_studio", help="Socket live data is disabled until network safety policy and fixtures are implemented."),
            ],
        },
    ]


__all__ = ["capability_catalog_payload"]
